# Spring Boot Cold Start Benchmark
# Measures full application startup time (JVM + Spring + App)
# Startup time is parsed from SpringBoot log: "Started DemoApplication in X.XXX seconds"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: springboot-coldstart-INSTANCE_SAFE
  namespace: benchmark
  labels:
    benchmark: springboot-coldstart
    instance-type: "INSTANCE_TYPE"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: springboot-coldstart
        instance-type: "INSTANCE_TYPE"
    spec:
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: INSTANCE_TYPE
        kubernetes.io/arch: ARCH
      tolerations:
        - key: "benchmark"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: springboot
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/springboot-petclinic:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "===== Spring Boot Cold Start: INSTANCE_TYPE ====="
              echo "Timestamp: $(date -Iseconds)"
              echo ""

              # Run java with output to file
              java -XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=60.0 -XX:+UseG1GC -jar /app/app.jar > /tmp/app.log 2>&1 &
              JAVA_PID=$!

              # Wait for startup message (max 180s)
              for i in $(seq 1 360); do
                if grep -q "Started.*Application" /tmp/app.log 2>/dev/null; then
                  cat /tmp/app.log
                  echo ""
                  echo "===== Complete ====="
                  kill $JAVA_PID 2>/dev/null
                  exit 0
                fi
                sleep 0.5
              done

              # Timeout
              echo "TIMEOUT: Application did not start"
              cat /tmp/app.log
              kill $JAVA_PID 2>/dev/null
              exit 1
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
