# Spring Boot Benchmark Job (wrk)
# HTTP Throughput 측정 - wrk를 사용하여 Spring Boot 서버 성능 테스트
---
apiVersion: batch/v1
kind: Job
metadata:
  name: springboot-benchmark-INSTANCE_SAFE
  namespace: benchmark
  labels:
    benchmark: springboot-benchmark
    instance-type: "${INSTANCE_TYPE}"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: springboot-benchmark
        instance-type: "${INSTANCE_TYPE}"
    spec:
      restartPolicy: Never
      # wrk runs on benchmark-client nodepool (c6in.8xlarge in zone c)
      nodeSelector:
        node-type: benchmark-client
      tolerations:
        - key: benchmark-client
          operator: Equal
          value: "true"
          effect: NoSchedule
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: springboot-server
                  instance-type: "${INSTANCE_TYPE}"
              topologyKey: "topology.kubernetes.io/zone"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: wait-for-springboot
          image: public.ecr.aws/docker/library/alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for Spring Boot server..."
              until wget -q --spider http://springboot-server-INSTANCE_SAFE:8080/ 2>/dev/null; do
                echo "Still waiting..."
                sleep 5
              done
              echo "Spring Boot server is ready!"
          env:
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
      containers:
        - name: benchmark
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/wrk:latest
          resources:
            requests:
              cpu: "1500m"
              memory: "4Gi"
          command:
            - /bin/sh
            - -c
            - |
              SPRINGBOOT_HOST="springboot-server-INSTANCE_SAFE"

              echo "===== Spring Boot Benchmark (wrk) ====="
              echo "Instance Type: ${INSTANCE_TYPE}"
              echo "Spring Boot Host: ${SPRINGBOOT_HOST}"
              echo ""

              # Warm-up (JIT compilation)
              echo "--- Warm-up Phase (30s) ---"
              wrk -t2 -c50 -d30s http://${SPRINGBOOT_HOST}:8080/ > /dev/null 2>&1
              echo "Warm-up complete"
              echo ""

              # Main page test
              echo "--- Main Page - 2 threads, 50 connections, 60s ---"
              wrk -t2 -c50 -d60s --latency http://${SPRINGBOOT_HOST}:8080/
              echo ""

              echo "--- Main Page - 2 threads, 100 connections, 60s ---"
              wrk -t2 -c100 -d60s --latency http://${SPRINGBOOT_HOST}:8080/
              echo ""

              # High load test
              echo "--- High Load - 2 threads, 200 connections, 30s ---"
              wrk -t2 -c200 -d30s --latency http://${SPRINGBOOT_HOST}:8080/
              echo ""

              echo "===== Spring Boot Benchmark Complete ====="
          env:
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
