# Spring Boot Application for Benchmark
# JVM startup time 및 throughput 측정
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-server-INSTANCE_SAFE
  namespace: benchmark
  labels:
    app: springboot-server
    benchmark: springboot
    instance-type: "${INSTANCE_TYPE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-server
      instance-type: "${INSTANCE_TYPE}"
  template:
    metadata:
      labels:
        app: springboot-server
        benchmark: springboot
        instance-type: "${INSTANCE_TYPE}"
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
      tolerations:
        - key: "benchmark"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: springboot
          # Simple Spring Boot app (multi-arch: amd64/arm64)
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/springboot-simple:latest
          # 리소스 제한 없음
          resources: {}
          ports:
            - containerPort: 8080
          env:
            # JVM 옵션 - 노드 전체 리소스 사용
            - name: JAVA_OPTS
              value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PrintFlagsFinal"
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-server-INSTANCE_SAFE
  namespace: benchmark
  labels:
    app: springboot-server
    instance-type: "${INSTANCE_TYPE}"
spec:
  selector:
    app: springboot-server
    instance-type: "${INSTANCE_TYPE}"
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
