# Redis Benchmark Job - 100M requests
# High volume benchmark for accurate throughput measurement
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-bench-INSTANCE_SAFE-runRUN_NUMBER
  namespace: benchmark
  labels:
    benchmark: redis-benchmark-100m
    instance-type: "${INSTANCE_TYPE}"
    run: "RUN_NUMBER"
spec:
  ttlSecondsAfterFinished: 7200  # 2 hours - enough time for log collection
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: redis-benchmark-100m
        instance-type: "${INSTANCE_TYPE}"
    spec:
      restartPolicy: Never
      nodeSelector:
        node-type: benchmark-client
      tolerations:
        - key: "benchmark-client"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: redis-server
                  instance-type: "${INSTANCE_TYPE}"
              topologyKey: "topology.kubernetes.io/zone"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: wait-for-redis
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/redis:8.4-alpine
          command:
            - /bin/sh
            - -c
            - |
              until redis-cli -h redis-server-INSTANCE_SAFE ping | grep -q PONG; do
                echo "Waiting for Redis server..."
                sleep 2
              done
              echo "Redis server is ready!"
      containers:
        - name: benchmark
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/redis:8.4-alpine
          resources:
            requests:
              cpu: "2000m"
              memory: "4Gi"
          command:
            - /bin/sh
            - -c
            - |
              REDIS_HOST="redis-server-INSTANCE_SAFE"

              echo "===== Redis 100M Benchmark ====="
              echo "Instance Type: ${INSTANCE_TYPE}"
              echo "Redis Host: ${REDIS_HOST}"
              echo "Run: RUN_NUMBER"
              echo "Timestamp: $(date -Iseconds)"
              echo ""

              # Redis server info
              echo "--- Redis Server Info ---"
              redis-cli -h ${REDIS_HOST} info server | head -20
              echo ""

              # Clear any existing data
              redis-cli -h ${REDIS_HOST} FLUSHALL

              # Main benchmark - 100M requests with pipeline for high throughput
              echo "--- 100M Requests Benchmark (Pipeline=16, Clients=50, Threads=4) ---"
              START=$(date +%s.%N)
              redis-benchmark -h ${REDIS_HOST} -c 50 -n 100000000 -P 16 --threads 4 -t set,get -q
              END=$(date +%s.%N)
              echo "Total time: $(echo "$END - $START" | bc) seconds"
              echo ""

              # Additional tests for comparison
              echo "--- SET Only (10M, Pipeline=16) ---"
              redis-benchmark -h ${REDIS_HOST} -c 50 -n 10000000 -P 16 --threads 4 -t set -q

              echo ""
              echo "--- GET Only (10M, Pipeline=16) ---"
              redis-benchmark -h ${REDIS_HOST} -c 50 -n 10000000 -P 16 --threads 4 -t get -q

              echo ""
              echo "--- INCR (10M, Pipeline=16) ---"
              redis-benchmark -h ${REDIS_HOST} -c 50 -n 10000000 -P 16 --threads 4 -t incr -q

              echo ""
              echo "--- No Pipeline Comparison (1M) ---"
              redis-benchmark -h ${REDIS_HOST} -c 50 -n 1000000 --threads 4 -t set,get -q

              echo ""
              echo "--- Latency Stats (SET) ---"
              redis-benchmark -h ${REDIS_HOST} -c 50 -n 1000000 -P 16 --threads 4 -t set --csv

              echo ""
              echo "--- Memory Stats ---"
              redis-cli -h ${REDIS_HOST} info memory | grep -E "used_memory|maxmemory|mem_fragmentation"

              echo ""
              echo "===== Redis 100M Benchmark Complete ====="
          env:
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
