# Redis Localhost Benchmark
# Redis 서버와 벤치마크를 같은 Pod에서 실행하여 네트워크 영향 배제
---
apiVersion: batch/v1
kind: Job
metadata:
  name: redis-local-INSTANCE_SAFE
  namespace: benchmark
  labels:
    benchmark: redis-local
    instance-type: "${INSTANCE_TYPE}"
spec:
  ttlSecondsAfterFinished: 7200  # 2시간 - 로그 수집 여유
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: redis-local
        instance-type: "${INSTANCE_TYPE}"
    spec:
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
      tolerations:
        - key: "benchmark"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: redis-benchmark
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/redis:8.4-alpine
          resources: {}  # 노드 전체 리소스 사용
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "===== Redis Localhost Benchmark ====="
              echo "Instance Type: ${INSTANCE_TYPE}"
              echo "Date: $(date -Iseconds)"
              echo ""

              # Redis 설정 파일 생성
              cat > /tmp/redis.conf << 'REDIS_CONF'
              bind 127.0.0.1
              port 6379
              protected-mode no
              daemonize yes
              pidfile /tmp/redis.pid
              logfile /tmp/redis.log

              # 메모리 설정
              maxmemory 0

              # 성능 최적화
              tcp-backlog 511
              tcp-keepalive 300

              # 지속성 비활성화
              save ""
              appendonly no

              # IO 스레드 (4 vCPU = 3 threads)
              io-threads 3
              io-threads-do-reads yes
              REDIS_CONF

              # Redis 서버 시작
              echo "--- Starting Redis Server ---"
              redis-server /tmp/redis.conf
              sleep 2

              # Redis 서버 상태 확인
              if ! redis-cli ping | grep -q PONG; then
                echo "ERROR: Redis server failed to start"
                cat /tmp/redis.log
                exit 1
              fi

              echo "Redis server started successfully"
              redis-cli info server | grep -E "redis_version|os:|arch_bits|tcp_port"
              echo ""

              # CPU/Memory 정보
              echo "--- System Info ---"
              echo "CPU: $(nproc) cores"
              echo "Memory: $(free -h | grep Mem | awk '{print $2}')"
              echo ""

              # Warmup (결과 버림)
              echo "--- Warmup (discarded) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 10000 --threads 3 -q > /dev/null 2>&1
              echo "Warmup complete"
              echo ""

              # Test 1: Standard Benchmark
              echo "--- Test 1: Standard Benchmark (50 clients, 100000 requests, 3 threads) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 100000 --threads 3
              echo ""

              # Test 2: Pipeline Benchmark
              echo "--- Test 2: Pipeline Benchmark (16 commands per pipeline) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 100000 -P 16 --threads 3
              echo ""

              # Test 3: High Concurrency
              echo "--- Test 3: High Concurrency (100 clients, 200000 requests) ---"
              redis-benchmark -h 127.0.0.1 -c 100 -n 200000 --threads 3
              echo ""

              # Test 4: Latency Distribution (SET)
              echo "--- Test 4: Latency Distribution (SET command) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 100000 -t set --threads 3 --csv
              echo ""

              # Test 5: Latency Distribution (GET)
              echo "--- Test 5: Latency Distribution (GET command) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 100000 -t get --threads 3 --csv
              echo ""

              # Test 6: Large Value (1KB)
              echo "--- Test 6: Large Value Test (1KB value, 50000 requests) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 50000 -d 1024 -t set,get --threads 3
              echo ""

              # Test 7: Large Value (4KB)
              echo "--- Test 7: Large Value Test (4KB value, 20000 requests) ---"
              redis-benchmark -h 127.0.0.1 -c 50 -n 20000 -d 4096 -t set,get --threads 3
              echo ""

              # Redis 서버 종료
              redis-cli shutdown nosave

              echo "===== Redis Localhost Benchmark Complete ====="
              echo "End Time: $(date -Iseconds)"
          env:
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
