# Nginx Benchmark Job using wrk
# HTTP throughput 및 latency 측정 - 3개 부하 레벨 (2t/100c, 4t/200c, 8t/400c)
---
apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-benchmark-INSTANCE_SAFE
  namespace: benchmark
  labels:
    benchmark: nginx-benchmark
    instance-type: "${INSTANCE_TYPE}"
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: nginx-benchmark
        instance-type: "${INSTANCE_TYPE}"
    spec:
      restartPolicy: Never
      # Benchmark client runs on dedicated benchmark-client nodepool (c6in.8xlarge)
      nodeSelector:
        node-type: benchmark-client
      tolerations:
        - key: "benchmark-client"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: nginx-server
                  instance-type: "${INSTANCE_TYPE}"
              topologyKey: "topology.kubernetes.io/zone"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: wait-for-nginx
          image: public.ecr.aws/docker/library/alpine:latest
          command:
            - /bin/sh
            - -c
            - |
              until wget -q -O - http://nginx-server-INSTANCE_SAFE/health 2>/dev/null | grep -q healthy; do
                echo "Waiting for Nginx server..."
                sleep 2
              done
              echo "Nginx server is ready!"
          env:
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
      containers:
        - name: benchmark
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/wrk:latest
          resources:
            requests:
              cpu: "4"
              memory: "4Gi"
          command:
            - /bin/sh
            - -c
            - |
              NGINX_HOST="nginx-server-INSTANCE_SAFE"

              echo "===== Nginx Benchmark: ${INSTANCE_TYPE} ====="
              echo "Timestamp: $(date -Iseconds)"
              echo ""

              # Warm-up
              echo "=== Warm-up (10s) ==="
              wrk -t2 -c50 -d10s http://${NGINX_HOST}/ > /dev/null 2>&1
              sleep 2

              # Test 1: 2 threads, 100 connections
              echo "=== wrk Test (2 threads, 100 connections, 30s) ==="
              wrk -t2 -c100 -d30s http://${NGINX_HOST}/
              echo ""

              sleep 2

              # Test 2: 4 threads, 200 connections
              echo "=== wrk Test (4 threads, 200 connections, 30s) ==="
              wrk -t4 -c200 -d30s http://${NGINX_HOST}/
              echo ""

              sleep 2

              # Test 3: 8 threads, 400 connections
              echo "=== wrk Test (8 threads, 400 connections, 30s) ==="
              wrk -t8 -c400 -d30s http://${NGINX_HOST}/
              echo ""

              echo "===== Complete ====="
          env:
            - name: INSTANCE_TYPE
              value: "${INSTANCE_TYPE}"
