# Nginx Server for Benchmark
# 정적 파일 서빙 성능 측정
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: benchmark
data:
  nginx.conf: |
    worker_processes auto;
    worker_rlimit_nofile 65535;

    events {
        worker_connections 10240;
        use epoll;
        multi_accept on;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        # 성능 최적화
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;

        keepalive_timeout 65;
        keepalive_requests 10000;

        # 버퍼 설정
        client_body_buffer_size 16k;
        client_header_buffer_size 1k;
        large_client_header_buffers 4 16k;

        # 로깅 비활성화 (성능 측정용)
        access_log off;
        error_log /var/log/nginx/error.log crit;

        # Gzip 비활성화 (순수 처리량 측정)
        gzip off;

        server {
            listen 80 reuseport;
            server_name _;

            location / {
                root /usr/share/nginx/html;
                index index.html;
            }

            # 작은 응답 테스트용
            location /small {
                return 200 "OK";
                add_header Content-Type text/plain;
            }

            # JSON 응답 테스트용
            location /json {
                return 200 '{"status":"ok","timestamp":$msec}';
                add_header Content-Type application/json;
            }

            # 헬스체크
            location /health {
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>Nginx Benchmark</title></head>
    <body>
    <h1>Nginx Benchmark Test Page</h1>
    <p>This is a test page for benchmarking Nginx performance.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server-INSTANCE_SAFE
  namespace: benchmark
  labels:
    app: nginx-server
    benchmark: nginx
    instance-type: "${INSTANCE_TYPE}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
      instance-type: "${INSTANCE_TYPE}"
  template:
    metadata:
      labels:
        app: nginx-server
        benchmark: nginx
        instance-type: "${INSTANCE_TYPE}"
    spec:
      nodeSelector:
        node.kubernetes.io/instance-type: "${INSTANCE_TYPE}"
      tolerations:
        - key: "benchmark"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nginx
          image: public.ecr.aws/docker/library/nginx:alpine
          resources: {}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server-INSTANCE_SAFE
  namespace: benchmark
  labels:
    app: nginx-server
    instance-type: "${INSTANCE_TYPE}"
spec:
  selector:
    app: nginx-server
    instance-type: "${INSTANCE_TYPE}"
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
