# Geekbench 6 - 표준화된 CPU/메모리 벤치마크
# 다른 시스템과 비교 가능한 점수 제공
# Pre-built multi-arch container image (arm64/amd64)
---
apiVersion: batch/v1
kind: Job
metadata:
  name: geekbench-INSTANCE_SAFE
  namespace: benchmark
  labels:
    benchmark: geekbench
    test-type: cpu
    instance-type: "INSTANCE_TYPE"
spec:
  ttlSecondsAfterFinished: 7200
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: geekbench
        test-type: cpu
    spec:
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: INSTANCE_TYPE
        kubernetes.io/arch: ARCH
      tolerations:
        - key: "benchmark"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: geekbench
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/geekbench:latest
          resources: {}
          command:
            - /bin/bash
            - -c
            - |
              echo "===== Geekbench 6 Benchmark ====="
              echo "Instance Type: INSTANCE_TYPE"
              echo "Architecture: $(uname -m)"
              echo ""

              echo "--- System Info ---"
              cat /proc/cpuinfo | grep -E "model name|Model" | head -1
              echo "vCPUs: $(nproc)"
              free -h | head -2

              echo ""
              echo "--- Running Geekbench 6 ---"
              /opt/geekbench/geekbench6 2>&1 | tee /tmp/geekbench-result.txt

              echo ""
              echo "--- Results Summary ---"
              # 점수 추출
              SINGLE=$(grep -i "Single-Core Score" /tmp/geekbench-result.txt | grep -oP '\d+' | tail -1)
              MULTI=$(grep -i "Multi-Core Score" /tmp/geekbench-result.txt | grep -oP '\d+' | tail -1)

              echo "SINGLE_CORE_SCORE: ${SINGLE:-0}"
              echo "MULTI_CORE_SCORE: ${MULTI:-0}"
              echo ""
              echo "Instance: INSTANCE_TYPE"
              echo "Architecture: $(uname -m)"

              echo ""
              echo "===== Geekbench Complete ====="
