# Passmark PerformanceTest Linux - 표준화된 벤치마크 점수
# runs-on.com과 직접 비교 가능한 CPU Single Thread / Multi Thread 점수
# Pre-built multi-arch container image (arm64/amd64)
---
apiVersion: batch/v1
kind: Job
metadata:
  name: passmark-INSTANCE_SAFE
  namespace: benchmark
  labels:
    benchmark: passmark
    test-type: cpu
    instance-type: "INSTANCE_TYPE"
spec:
  ttlSecondsAfterFinished: 7200
  backoffLimit: 0
  template:
    metadata:
      labels:
        benchmark: passmark
        test-type: cpu
    spec:
      restartPolicy: Never
      nodeSelector:
        node.kubernetes.io/instance-type: INSTANCE_TYPE
        kubernetes.io/arch: ARCH
      tolerations:
        - key: "benchmark"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: benchmark
                    operator: Exists
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: passmark
          image: 180294183052.dkr.ecr.ap-northeast-2.amazonaws.com/benchmark/passmark:latest
          resources: {}
          command:
            - /bin/bash
            - -c
            - |
              echo "===== Passmark PerformanceTest Linux ====="
              echo "Instance Type: INSTANCE_TYPE"
              echo "Architecture: $(uname -m)"
              echo ""

              echo "--- System Info ---"
              cat /proc/cpuinfo | grep -E "model name|Model" | head -1
              echo "vCPUs: $(nproc)"
              free -h | head -2

              cd /opt/passmark

              echo ""
              echo "--- Running Passmark CPU Benchmark ---"
              export TERM=xterm
              ./pt_linux -r 1 2>&1 | tee /tmp/passmark-result.txt

              echo ""
              echo "--- Results Summary ---"
              # CPU Mark 결과 파싱
              CPU_MARK=$(grep -i "CPU Mark" /tmp/passmark-result.txt | grep -oP '\d+' | head -1)

              # 세부 점수 추출
              if [ -f "results_cpu.yml" ]; then
                cat results_cpu.yml
              fi

              echo ""
              echo "CPU_MARK: ${CPU_MARK:-0}"
              echo "Instance: INSTANCE_TYPE"
              echo "Architecture: $(uname -m)"

              echo ""
              echo "===== Passmark Complete ====="
